Add database
naykama/java-filmorate_old pull request #6
Opened 2024-01-21 07:38 UTC by naykama

Добрый день!

2024-01-21 10:58 UTC, Frilock requested changes
Добрый день, комментарии в коде оставил

2024-01-21 10:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Лишняя аннотация

2024-01-21 10:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Slf4j
Лишняя аннотация

2024-01-21 10:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private final  Map<Long, Film> filmMap = new HashMap<>();
Поехало форматирование

2024-01-21 10:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private final Map<Integer, Genre> genres = new HashMap<>();
Что то Коллекций других сущностей тут не должно быть, они должны быть только в своих хранилищах

2024-01-21 10:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Лучше использовать StringUtils.isBlank

2024-01-21 10:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +                if (userRows.getString("status").equals("unconfirmed")) {
Вообще такие проверки опасны, лучше использовать для сравнения енамы, кроме того, чтобы NPE не получить сначала сравнивайте значение которое точно есть - "unconfirmed".equals...

2024-01-21 10:58 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Зачем писать  IF NOT EXISTS если вы строчкой выше все удалили?

2024-01-21 10:58 UTC, Frilock commented on src/main/resources/schema.sql
> +    email varchar,
Для полей нужно задавать размерность, продумайте этот момент

2024-01-21 10:58 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmDbStorageTest.java
> +        scripts = "../../../../data.sql"
в 1 строчку влезает

2024-01-21 10:58 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/UserDbStorageTest.java
> +//                .usingRecursiveComparison()
Закоментированный код оставлять не нужно

2024-01-22 17:10 UTC, Frilock approved these changes
Принято

2024-01-22 17:10 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDbStorage.java
> +    Map<Integer, Genre> genres = new HashMap<>();
Модификатор приватный?

2024-01-24 11:16 UTC, naykama commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDbStorage.java
> +    Map<Integer, Genre> genres = new HashMap<>();
да, private final

2024-01-24 11:17 UTC, merged